### ISSUE TITLE
Support Binary Numbers

### ISSUE THREAD

**Issue by iamrecursion** [LiamRiddell/obsidian-solve#2]
I just want to say that this is really cool so far! I've been trying it in my vault and already getting some good use out of it.

One thing that would be really cool to see is support for binary number literals, as a good arbitrary-precision calculator is hard to find!

**Comment by LiamRiddell** [comment]
@iamrecursion 👋 Thank you for trying solve and requesting a the first feature! I'm delighted that you're enjoying it and finding value in the early stages of development. Your input is appreciated!

Regarding the added functionality, that sounds promising. Could you share your vision for the expected features?

In terms of the format, are you suggesting that `0b00010100` would be equivalent to `20` in decimal?

For implementation, we could adopt a similar strategy as the `Vector` providers and keep this new functionality isolated. One challenge I encountered while developing `Solve` is that the current hex support offers lower precision compared to the `long` data type due to the nature of `number` in JavaScript. This limitation can potentially be resolved by utilising [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt). However, it's crucial to note that `BigInt` and `number` operations can't be mixed seamlessly.

**Comment by LiamRiddell** [comment]
Yeah, this would be really useful. I agree, I'm going to aim to add this as one of the release towards 1.0.0. Thank you for such clear message. It really helps with requirements gathering.

**Comment by iamrecursion** [comment]
Glad to help! Thank _you_ for such a cool plugin! It works so seamlessly in Obsidian already!

**Comment by LiamRiddell** [comment]
Incoming in 1.0.0, in beta state 👍 

![image](https://github.com/LiamRiddell/obsidian-solve/assets/3812154/0ba3909c-5260-4404-8787-26ad2bb2d64a)

**Comment by iamrecursion** [comment]
Oh _heck_ yes!!! Thanks so much, Liam!
