### ISSUE TITLE
[Bug] Additional extra space before result in explicit mode 

### ISSUE THREAD

**Issue by Dvornik** [LiamRiddell/obsidian-solve#59]
**Describe the bug**
Additional extra space before result when Explicit mode is ON

**To Reproduce**
1. Turn on Explicit mode
2. Write `2 + 2 =`
3. Solve adds one extra space before result

**Expected behavior**
No extra space before result

**Screenshots**
![image](https://github.com/user-attachments/assets/047c8800-d3af-423d-a9b5-3b3a943f6b7e)

**Obsidian**
- Version:  1.6.7 
- Platform: Desktop, Mobile

Thank you very much for this awesome things! I use it every day and I love it!

**Comment by Dvornik** [comment]
Fixed it with Style Settings plugin:

<img width="775" alt="image" src="https://github.com/user-attachments/assets/27adea28-5cea-4bac-ae5e-dbd09602f62c">

**Comment by LiamRiddell** [comment]
@Dvornik Sorry for late reply, I have less time to focus on this project due to new role.

I'm glad you solved the problem. 

I'd still be keen to look into this but I think it stems from there is a space inserted after the = sign and then as you've correctly pointed out the left margin from the custom styles.

I maybe remove the space after equals so the user can control the margins.

**Comment by Dvornik** [comment]
> I maybe remove the space after equals so the user can control the margins.

Thank you! That would be the best solution. I noticed that with Explicit mode is OFF, there's an extra space **before the equals sign** here too:
<img width="138" alt="image" src="https://github.com/user-attachments/assets/9feeff6e-ed0f-4f7b-9c98-485b7671a737">
Zero left margin from the custom styles can fix this also.

**Comment by LiamRiddell** [comment]
I've instead removed the left padding as it's more consistent on default settings of Solve. These can still be overridden. This change will go out as part of #61
